### ISSUE TITLE
My thing broken

### ISSUE THREAD

**Issue by FlaminGolmao** [Kalejin/DCSB#38]
when I  open it it doesn't work and it says a bunch of stuff and at the top it says unhandled exception
![Capture](https://user-images.githubusercontent.com/56096209/66086849-7204d680-e543-11e9-9bb0-0c582594f4a7.PNG)

**Comment by Jorelm** [comment]
I'm getting this same error. 
![DCSBerror](https://user-images.githubusercontent.com/60859888/74112433-d2db9580-4b59-11ea-8324-2016a8724ed8.jpg)

**Comment by Todinger** [comment]
Well, I have a solution but it requires changing the code a bit.
In the file DCSB.Input\RawKeyboard.cs, change line #81:
`var deviceDesc = Win32.GetDeviceDescription(deviceName);`
To:
`string deviceDesc = null;`
`try`
`{`
`deviceDesc = Win32.GetDeviceDescription(deviceName);`
`}`
`catch`
`{`
`continue;`
`}`

Then save and run.
Worked for me.

**Comment by Kalejin** [comment]
This should be fixed in version 4.0.0.9.

**Comment by HenryHering** [comment]
I somehow have a similar problem. When I first used DCSB, it worked fine, but after a day of using it, I got this error message. Sometimes it's the top message, but sometimes it's the other one. I am using version 4.0.0.9 and I also tried to uninstall DCSB and delete the folder in programdata and reinstall it, but the same problem occurred. Even if I run it with admin rights, it still shows up after a few seconds and when I close it DCSB closes too.
I don't know what the other process might be that uses the config_tmp.xml file as written in the second image.
Can anyone help me? I hope this will be fixed soon.

![grafik](https://user-images.githubusercontent.com/64810734/81015616-4a6e4780-8e5f-11ea-9d4f-a6e479e68326.png)
![grafik](https://user-images.githubusercontent.com/64810734/81015713-74276e80-8e5f-11ea-8fa6-315b847ee6c8.png)
